[package]
name = "password-generator"
version = "1.2.0"
edition = "2021"


[dependencies]
clap = { version = "4.3.2", features = ["derive"] }
csv = "1.2.2"
itertools = "0.10.5"
passwords = "3.1.13"
serde = { version = "1.0.163", features = ["derive"] }
